### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Zimmi48**
Given that the README gets displayed in the Marketplace listing, should we move the `TODO/IFNEEDBE` section somewhere else?

### CODE REVIEW

**Comment by erikmd** [comment]
Hi @Zimmi48, thanks for your proofread!

> Given that the README gets displayed in the Marketplace listing, should we move the TODO/IFNEEDBE section somewhere else?

Good point; actually the last two items looked unneeded to me now so I removed these, but I addressed the first item by adding some links on the .opam file format. (I also pushed two other commits that looked necessary to me.)

Two questions before merging this PR:

1. do you know if there's somewhere a page that gives some guidelines on the `coq-….opam` files (e.g. the keywords that are required for PRs to be accepted in coq/opam-coq-archive ?)
otherwise, maybe the two links I added are enough anyway:
    - https://github.com/coq-community/templates#readme
    - https://opam.ocaml.org/doc/Packaging.html#The-file-format-in-more-detail

2. are you still OK with the naming of `custom_script` and the related remark?
    > *Note-2: this option is named `custom_script` rather than `script` or
    > `run` to discourage changing its recommended, default value, while
    > keeping the flexibility to be able to change it.

    as when v1.0.0 will be released, we won't be able to rename it if need be before `v2.0.0` ;-)

**Comment by Zimmi48** [comment]
1. There's https://coq.inria.fr/opam-packaging.html
2. Yes, I think it is good.

**Review by Zimmi48 — COMMENTED** [review]
LGTM but linking to https://coq.inria.fr/opam-packaging.html is definitely a must.

**Comment by erikmd** [comment]
> LGTM but linking to https://coq.inria.fr/opam-packaging.html is definitely a must.

Thanks @Zimmi48; feel free to add a commit in this branch that takes this URL into account, and we'll merge afterwards.

**Comment by Zimmi48** [comment]
I can't do it right now, so feel free to do it yourself if you'd like to close this today.

**Comment by erikmd** [comment]
Thanks @Zimmi48 (FYI I just added the text below)

> This `.opam` file can then serve as a basis for submitting releases in [coq/opam-coq-archive](https://github.com/coq/opam-coq-archive), and related guidelines (including the required **`.opam` metadata**) are available in <https://coq.inria.fr/opam-packaging.html>.
> 
> More details can be found in the [opam documentation](https://opam.ocaml.org/doc/Packaging.html#The-file-format-in-more-detail).

**Comment by erikmd** [comment]
Just FYI, the coq-problem-matcher is OK as well now (will open a dedicated PR)

**Pull request merged**
