### PR TITLE
Don't pull `$COQ_IMAGE` if it exists locally

### LINKED ISSUE #80: Document how to ensure a single Coq version is used across multiple invocations of the action
Fiat Crypto has [a workflow](https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/docker-coq.yml) where we invoke the action multiple times, as in
```
    - name: deps
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI ALLOW_DIFF COQCHKEXTRAFLAGS
        custom_script: etc/ci/github-actions-docker-make.sh -j2 deps
    - name: all-except-generated
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI ALLOW_DIFF COQCHKEXTRAFLAGS
        custom_script: etc/ci/github-actions-docker-make.sh ${EXTRA_GH_REPORTIFY} -j2 all-except-generated
    - name: generated-files
      run: etc/ci/github-actions-make.sh ${EXTRA_GH_REPORTIFY} -f Makefile.examples -j2 generated-files
      if: github.event_name == 'pull_request' || ${{ matrix.env.COQ_VERSION }} != 'master'
    - run: tar -czvf generated-files.tgz fiat-*/
      if: ${{ failure() }}
    - name: upload generated files
      uses: actions/upload-artifact@v3
      with:
        name: generated-files-${{ matrix.env.COQ_VERSION }}
        path: generated-files.tgz
    - name: standalone-haskell
      run: etc/ci/github-actions-make.sh -f Makefile.standalone -j1 standalone-haskell GHCFLAGS='+RTS -M6G -RTS'
    - name: validate
      uses: coq-community/docker-coq-action@v1
      with:
        coq_version: ${{ matrix.env.DOCKER_COQ_VERSION }}
        ocaml_version: ${{ matrix.env.DOCKER_OCAML_VERSION }}
        export: CI ALLOW_DIFF COQCHKEXTRAFLAGS
        custom_script: etc/ci/github-actions-docker-make.sh TIMED=1 validate COQCHKFLAGS="-o ${COQCHKEXTRAFLAGS}"
      if: env.SKIP_VALIDATE == '' && github.event_name != 'pull_request'
```
This has a couple advantages:
- we can order steps the way we want, which is not possible if we can only invoke the docker action once (unless I want to figure out how to hand-code a replacement for actions/upload-artifact from inside docker, which I don't)
- we can make use of other actions, like installing Haskell and uploading artifacts
- we get more readable logs because we can make separate steps

However, there's a big downside, which is that sometimes "coq.dev" changes meaning between one step and the next, and this causes our CI to do duplicative work or fail outright.

I'd like to be able to somehow record the particular commit of Coq or docker image or something in a file or GitHub environment variable (I think one step can persistently modify the environment for subsequent steps by writing to a file), but I'm not sure how to get the relevant information from inside docker, nor how to tell the next step to use the same version.  How can I set up my script to do this?

### PR DESCRIPTION
**Pull request by erikmd**
Close #80

### CODE REVIEW

**Comment by JasonGross** [comment]
This seems to break with
```
  Error: No such image: coqorg/coq:dev-ocaml-default
  
  Error response from daemon: manifest for coqorg/coq:dev-ocaml-default not found: manifest unknown: manifest unknown
```
See https://github.com/mit-plv/fiat-crypto/actions/runs/3517325936/jobs/5894966269 and https://github.com/mit-plv/fiat-crypto/pull/1517

**Comment by erikmd** [comment]
@JasonGross sorry, my bad… I had added this feature on top on a too-old master branch 😅 so I just rebased;
could you please rerun your test PR?
Thanks again 👍👍

**Comment by JasonGross** [comment]
Seems to build, at least: https://github.com/mit-plv/fiat-crypto/actions/runs/3517325936/jobs/5901070228

**Comment by erikmd** [comment]
OK @JasonGross; unfortunately your run did not went through the second docker-coq-action call.

Do you want that I wait for a second test of yours?

or do you prefer that I just add a more thorough test (beyond the one below) then do a release?
https://github.com/coq-community/docker-coq-action/blob/1e4f934e838eb03b98205f02be7d5408c3ced37f/.github/workflows/python-demo.yml#L81-L84
→ https://github.com/coq-community/docker-coq-action/actions/runs/3518557133/jobs/5897601262#step:3:299

**Comment by erikmd** [comment]
OK @JasonGross so I pushed a more thorough test, and everything looks good to go:

https://github.com/coq-community/docker-coq-action/actions/runs/3536674876/jobs/5935937276#step:5:208

So let's release 1.4.1 now…

**Pull request merged**
