### PR TITLE
uninstall: always yes

### PR DESCRIPTION
**Pull request by liyishuai**
in case after_script installed some dependants

### CODE REVIEW

**Comment by erikmd** [comment]
Thanks @liyishuai, LGTM… but the PR is incomplete → you should also update:

1.

https://github.com/coq-community/docker-coq-action/blob/44a09e0899c937b06f061fbbbb1bb6083aac7d90/README.md?plain=1#L83

2.

https://github.com/coq-community/docker-coq-action/blob/44a09e0899c937b06f061fbbbb1bb6083aac7d90/README.md?plain=1#L307

3.

https://github.com/coq-community/docker-coq-action/blob/44a09e0899c937b06f061fbbbb1bb6083aac7d90/README.md?plain=1#L338

Then, I'll do a release.

**Comment by erikmd** [comment]
And even if some changes are very small like these, I prefer that the PRs are merged by the maintainers (@Zimmi48 @erikmd), as it is the standard practice in coq-community (?)

**Comment by Zimmi48** [comment]
> And even if some changes are very small like these, I prefer that the PRs are merged by the maintainers (@Zimmi48 @erikmd), as it is the standard practice in coq-community (?)

Some repositories are more lax than others. We could set up branch protection rules here. WDYT?

**Comment by erikmd** [comment]
I thought every master branch of every coq-community project was protected like this, so it appears this is not the case;
so yes, I will configure this now. [Edit: done]

**Comment by Zimmi48** [comment]
Maybe we should document somewhere (manifesto FAQ?) what the default is and what the options are? cc @palmskog

**Comment by palmskog** [comment]
My view: branch protection is definitely something that maintainers can decide about, and we should probably set it up for all "critical" projects, such as this and the other Docker projects (and maybe use it for all Coq Platform projects as well?).

But good to document this, and also best practices regarding merging PRs.

**Comment by erikmd** [comment]
@palmskog Yes;

FTR, here is the screenshot of the settings currently applied for `coq-community/docker-coq-action`'s `master` branch:

2022-10-13_github_coq-community_docker-coq-action_protected_branches

**Comment by palmskog** [comment]
@erikmd do you really have to add people explicitly under "People, teams or apps with push access"? I thought we could have the convention that everyone that is supposed to have push access is either an Admin or a Coq-community member with the Maintain role [for the repo in question].

**Comment by Zimmi48** [comment]
It's actually useless to *repeat* people here since the list already includes all organization or repository admins.

It is also not useful to check "Restrict pushes that create matching branches" for a pattern which is the branch name of an already existing branch. This is more useful when you want to prevent any other branch, or any new release branch from being created on the repository, like we do in Coq. Here this would be useful for instance if you transformed the `v1` rule into `v[0-9].*` or something like this (I don't recall the exact syntax).

Anyway, this highlights even more the need to document this.

**Comment by erikmd** [comment]
@palmskog @Zimmi48 thanks for your comments, yes I was already aware that the crossed checkboxes of the config I shared were sub-optimal, but it didn't induce any bug… admittedly, if we want to document a standard, cross-organization configuration, we should better have a polished one.
Anyway while we are on it, I refactored the config of docker-coq-action accordingly, and replaced `v1` with `v*` [(doc1)](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule),[(doc2)](https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch)

Regarding the checkbox `Require signed commits`, it looked important to me for docker-coq-action, but I wouldn't put it forth for other coq-community projects at first sight.

**Pull request merged**
