### PR TITLE
Move startGroup/endGroup constructs to individual fields

### LINKED ISSUE #34: New fine-grained customization does not allow groups within each section
The new value for custom_script that includes all the sections surrounds each one with a `startGroup` with a generic name:

```
startGroup before_install dependencies
  {{before_install}}
endGroup
startGroup install dependencies
  {{install}}
endGroup
startGroup after_install dependencies
  {{after_install}}
endGroup
startGroup before_script
  {{before_script}}
endGroup
startGroup script
  {{script}}
endGroup
startGroup after_script
  {{after_script}}
endGroup
startGroup uninstall
  {{uninstall}}
endGroup
```

Those names are a bit annoying on their own, but worse GitHub actions doesn't seem to support nested groups so they forbid adding any user groups (unless you rewrite `custom_script`, of course).

### PR DESCRIPTION
**Pull request by erikmd**
* **Kind:** fix
* Closes #34

Impact:
* this slightly changes defaults values w.r.t. v1.2.0
* but this is fully backward-compatible w.r.t. v1.1.0
* and this makes it possible to customize group names (that cannot be nested)

I can readily do a point release if you want @tchajed ; otherwise tomorrow Saturday :)

### CODE REVIEW

**Review by tchajed — APPROVED** [review]
LGTM, thanks!

**Comment by tchajed** [comment]
Up to you when to merge - I already effectively did this by overriding `custom_script`, once this is merged I can stop doing that.

**Comment by erikmd** [comment]
BTW I've added some extra documentation on startGroup/endGroup (to document that they not only create foldable groups using the standard GHA feature, but also compute the intermediate elapsed time).

I'd like to merge this PR ASAP as it is a *fix*, however I'd be glad to have some review for the doc I have added (in a2a4cb7d443f6586065c4d0652605620e3b0f312)

Cc @Zimmi48 FYI

**Comment by erikmd** [comment]
In the meantime, note that even if this PR is not yet merged, the docker-coq-action can already be used as is by specifying the temporary branch `fix-groups`:

```yaml
- uses: coq-community/docker-coq-action@fix-groups
```

**Review by Zimmi48 — APPROVED** [review]
LGTM but please fix the example overriding `before_script`, `script` and `uninstall` to create groups (in particular, this would replace the `echo Workaround...`).

**Comment by erikmd** [comment]
Fixed, and will now release v1.2.1. Thanks @Zimmi48 for your review!

**Comment by erikmd** [comment]
@tchajed 
> Up to you when to merge - I already effectively did this by overriding `custom_script`, once this is merged I can stop doing that.

Release done: https://github.com/coq-community/docker-coq-action/releases/tag/v1.2.1; so you'll be able to use the default `custom_script` from now on :)

**Comment by tchajed** [comment]
Thanks @erikmd, I'm now taking advantage of this in Perennial.

**Pull request merged**
