### PR TITLE
Prepend 'exec 2>&1' to custom_script to untangle output

### PR DESCRIPTION
**Pull request by erikmd**
* This patch workarounds GitHub Actions unflushed std(out/err) output.

### CODE REVIEW

**Review by Zimmi48 — COMMENTED** [review]
It's hard for me to review because I didn't know about the issue and I don't understand the fix. But I trust you on this.

**Comment by erikmd** [comment]
OK, so FTR: the fact is that the lines automatically added by `set -x` are sent to stderr, while the main output is sent to stdout, and the issue was that GHA does not seem to flush printing to these two different channels, resulting (before this PR) is a distracting un-sync.

For example, beforehand:
https://github.com/erikmd/docker-coq-github-action-demo/runs/1456333460?check_suite_focus=true#step:4:188
```
some value
+ (script @ line 4) $ printf '%s\n' 'some value'
```

henceforth:
https://github.com/erikmd/docker-coq-github-action-demo/runs/1456454613?check_suite_focus=true#step:4:188
```
+ (script @ line 4) $ printf '%s\n' 'some value'
some value
```

**Comment by Zimmi48** [comment]
OK, so basically, you redirect them to the same channel to ensure they are printed in order. Sounds good to me. However, this might also be worth to open a feedback ticket with GitHub about this: https://support.github.com/contact/feedback

**Comment by erikmd** [comment]
> this might also be worth to open a feedback ticket with GitHub about this: https://support.github.com/contact/feedback

Done.

**Pull request merged**
